### PR TITLE
Attach checksums as build artifacts

### LINKED ISSUE #30: Attach checksums as build artifacts
It seems that the current implementation does not attach the created checksums as build artifacts. At least, it did not work out of the box for me and I do not see documentation for it.

It would be nice to attach generated checksums as build artifacts, so that they could automagically be uploaded to the Maven repository. That would provide an easy way to enrich the current MD5 and SHA1 checksums.

### PR DESCRIPTION
**Pull request by gehel**
Added a new parameter `attachChecksums` which enables attaching generated files as build artifacts.

Fixes #30

### CODE REVIEW

**Comment by gehel** [comment]
Hello !

Any chance that you would merge this and make a new release ? Do you want some help on the project ? Should I fork and create my own release ?

Thanks for your help !

**Comment by gastaldi** [comment]
Looks like I missed this PR. I created a new PR fixing #30 too: https://github.com/nicoulaj/checksum-maven-plugin/pull/33

This fix is very important so we can adopt this plugin in our parent POM. Please merge one of them.

Best Regards,

George Gastaldi

**Comment by gehel** [comment]
@nicoulaj Seems we have 2 PR opened to allow attaching checksums as build artifacts. It looks to me that this is a good indication of an important feature. Can I do anything to ensure this is merged? Is there anything missing from those PR that you would like to see?

Thanks for your help!

**Comment by bondolo** [comment]
I have concluded that there is probably will be no response and it is probably time to fork.

**Comment by gastaldi** [comment]
Absolutely. It´s a pity that the owner just ignored contributions.

**Comment by gehel** [comment]
I agree, time to fork (unless @nicoulaj wants to keep this repo alive). Anyone wants to take ownership? On my side, it would take me some delay to configure publication to maven central (not much free time for the next weeks), but I can try...

**Comment by nicoulaj** [comment]
I'll try to take care of this today or tomorrow, sorry guys.

**Comment by nicoulaj** [comment]
I have given commit access to @bondolo and @gehel. Feel free to merge PRs and ping me when I can do a release.

**Comment by gehel** [comment]
That's great! It took some time, but I'm really happy to see this plugin evolve!

**Comment by bondolo** [comment]
Thank you!

**Comment by bondolo** [comment]
Do either of you  @gehel or @gastaldi have a reason to prefer your PR over the other for attach checksum? Which one should we go ahead with?

**Comment by gastaldi** [comment]
Hi,

I don't have any preference. Both PRs look good to me.

Thanks
Em 02/02/2016 17:08, "Mike Duigou" <notifications@github.com> escreveu:

**Comment by nicoulaj** [comment]
Thanks, I have released version 1.3.

**Pull request merged**
